### Obtener todos los usuarios
GET http://localhost:3000/users
###

### Obtener un usuario específico por su id
GET http://localhost:3000/users/1
###

### Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mario Sabillon",
  "username": "msabillon",
  "email": "sabillon1@unah.hn",
  "phone": 1234567890,
  "role": "viewer"
}
###

### Actualizar un usuario existente
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "Usuario Actualizado",
  "username": "usuarioAct",
  "email": "usuario.actualizado@unah.hn",
  "phone": 9876543210,
  "role": "admin"
}
###

### Eliminar un usuario por su id
DELETE http://localhost:3000/users/1
###